name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: egemengzr
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul

          repositories_affiliations: owner, collaborator, organization_member
          repositories_private: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 30
          plugin_activity_filter: all

          plugin_followup: yes
          plugin_followup_sections: user

          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 10
          plugin_languages_threshold: 1%

          plugin_lines: yes
          plugin_traffic: yes
          plugin_contributors: yes
          plugin_contributors_contributions: 100
